"""expand detection schema

Revision ID: 3846f04cb077
Revises: 
Create Date: 2025-11-12 15:08:37.682877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3846f04cb077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('weights_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_detection_model_name_version')
    )
    with op.batch_alter_table('detection_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_models_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_last_login_at'), ['last_login_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_last_analyzed_at'), ['last_analyzed_at'], unique=False)
        batch_op.create_index('ix_media_files_user_created', ['user_id', 'uploaded_at'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=120), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index('ix_system_logs_action_created', ['action_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_user_id'), ['user_id'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('prediction_label', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['detection_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index('ix_analysis_results_media_created', ['media_file_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_media_file_id'), ['media_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_prediction_label'), ['prediction_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_prediction_label'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_model_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_media_file_id'))
        batch_op.drop_index('ix_analysis_results_media_created')

    op.drop_table('analysis_results')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_user_id'))
        batch_op.drop_index('ix_system_logs_action_created')

    op.drop_table('system_logs')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index('ix_media_files_user_created')
        batch_op.drop_index(batch_op.f('ix_media_files_last_analyzed_at'))
        batch_op.drop_index(batch_op.f('ix_media_files_file_type'))
        batch_op.drop_index(batch_op.f('ix_media_files_checksum'))

    op.drop_table('media_files')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_last_login_at'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('detection_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_models_is_active'))

    op.drop_table('detection_models')
    # ### end Alembic commands ###
