"""add user status field

Revision ID: 3bc2a9cd1469
Revises: 3846f04cb077
Create Date: 2025-11-12 21:20:49.996827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc2a9cd1469'
down_revision = '3846f04cb077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support adding NOT NULL columns with defaults easily
    # So we add it as nullable first, set values, then optionally make it NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
